name: Java CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: {% data reusables.actions.action-checkout %}
    - name: Set up JDK 11
      uses: {% data reusables.actions.action-setup-java %}
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Ant
      run: ant -lib yuicompressor-2.4.8.jar -f build.xml